# Generated by Django 4.0 on 2021-12-13 06:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profiles/userDefault.png', null=True, upload_to='profiles/')),
                ('social_github', models.URLField(blank=True, max_length=255, null=True)),
                ('social_twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('social_linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('social_youtube', models.URLField(blank=True, max_length=255, null=True)),
                ('social_website', models.URLField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'userProfile',
                'verbose_name_plural': 'userProfiles',
            },
        ),
    ]
