# Generated by Django 4.0 on 2021-12-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message_read_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['name'], 'verbose_name': 'userProfile', 'verbose_name_plural': 'userProfiles'},
        ),
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
